### ISSUE TITLE
Use with distributed (hg) version control systems help

### ISSUE THREAD

**Issue by moorecm** [vmware/jenkins-reviewbot#18]
I'm currently trying to use this plugin with Mercurial.  I'm not sure what means the plugin "gets the patch" from reviewboard and/or what it tries to do with it internally but I'm guessing it's just grabbing some kind of revision identifier.

The setup I have is 1 shared repository and multiple developers who have local clones of that repository.  What we want to do is commit changes in our local repositories, post a review, and have reviewbot comment with the relevant metrics.  After approval, the developer can push the changeset to the shared repository.  So far, we love this plugin!

Now, the problem we have is that without serving each developer's local repo., the job workspaces (configured to use the shared repo.) are not picking up the changes.  That means, we're seeing the results of the stable, shared repo. automation being posted to a review for a local change.

It appears to work if we serve our local repos. and copy jobs for each of the developers but that is a lot of maintenance overhead.  And at this point, I have not verified that it isn't just grabbing the tip and running tests completely independent of whatever was posted to ReviewBoard.

Can you elaborate on how to configure a job in Jenkins to get a workspace with the patch from ReviewBoard applied?  Maybe I have something misconfigured.  Maybe it is just broken for Mercurial?

If I could get just 1 job to patch the workspace I can clone it for any other downstream jobs easily.  Let me know if there is anything I can do to help with this.  At a minimum, I think the plugin needs some additional documentation that includes an example config. or two.  Thanks!

**Comment by moorecm** [comment]
Digging a little deeper, I'm not seeing the patch written to disk anywhere (for Mercirial builds).  I did accidentally have the job trigger for a Perforce review and it wrote out fileParameters/patch.diff in the build directory.

Browsing the source, I noticed that it used to use the raw url for reviewboard.  This url appears to still work using ReviewBoard 2.0.13:
http://<host>/reviewboard/r/<review id>/diff/raw/

I'm interested in why the approach has changed.  Perhaps the plugin should try the raw url and if that doesn't work, try the other approach.

As a workaround, I might try to write my own script to download the patch and apply it.  Then I would just use this plugin as a trigger and for posting comments to the review.

**Comment by moorecm** [comment]
Unless I'm missing something, I just don't see how this plugin is getting a patch file from reviewboard at all.  The url it appears to be hitting (.../api/review-requests/REVIEW_ID/diffs/REVISION_COUNT/) is serving up XML for my GET requests.  The plugin appears to be expecting a patch file.

The REST API does provide direct access to patched-file and original-file.  With that, a simple diff would result in the patch.

Again, I feel like I must be missing something.  Something in the request header, maybe?  If this API isn't getting a patch, I would expect the plugin to be broken for all SCMs--and I don't think that would have gone undetected for so long.

**Comment by moorecm** [comment]
The documentation says that a patch is returned if the content-type is "text/x-patch":
https://www.reviewboard.org/docs/manual/dev/webapi/2.0/resources/diff/

My browser is always getting XML and my Python script below is always getting JSON.  I have yet to get a patch out of the api.

import requests
r = requests.get("http://HOST/reviewboard/api/review-requests/REVIEW_ID/diffs/REVISION_NUMBER/", headers={"content-type":"text/x-patch"})
print(r.headers)
print(r.content)  # expecting a patch file but I keep getting JSON
print(r.status_code)

**Comment by yardena** [comment]
You need to use Accept header instead of content-type, like (in Java)
request.setRequestHeader("Accept", "text/x-patch")

**Comment by moorecm** [comment]
Thank you.  I was just about to respond with a note saying that I managed to get it to work using accept rather than content-type.  This means ReviewBoard is able to serve up the patch.

I'm not seeing anything in the console output about applying a patch.  Nor am I finding the patch on disk.  Which job would be the one that handles the patching?

I have a job used to poll reviewboard, which just invokes another job (the parameterized by review url one).  The parameterized job invokes another job using the Build Flow plugin and reports the results back to the review.  All of this appears to be working except the workspaces (for any of the jobs) are not patched with the changes.

I'm trying my best to narrow the issue down.  If there's anything specific I can do to help or if you have any tips on where to look, just let me know.

**Comment by yardena** [comment]
The job with the review parameter should have patch.diff file in the workspace

**Comment by moorecm** [comment]
So, that should mean that testing this is as easy as running the parametrized job and specifying a review url.

What I did was created a new Freestyle build job and configured it to be parameterized by review url, to invoke another job, and to report the results to the review.  This time, it did create the patch file!  So, there seems to be a problem when using a Build Flow job:
https://wiki.jenkins-ci.org/display/JENKINS/Build+Flow+Plugin

This is easy to workaround because the Freestyle build job can just invoke a Build Flow job...  That said, I'm not sure why it doesn't work and it may be worth recommending such a configuration in README.md.

Now, I'm hitting the apply patch failure:
Applying the diff
Failed to apply patch due to:
java.io.IOException: Failed to patch /usr0/jenkins/jobs/ting-trunk job02b -- parameterized build/workspace/test/pan/log/test_panlog.py
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ApplyTask.invoke(ReviewboardParameterValue.java:250)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ApplyTask.invoke(ReviewboardParameterValue.java:240)
	at hudson.FilePath.act(FilePath.java:989)
	at hudson.FilePath.act(FilePath.java:967)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue.applyPatch(ReviewboardParameterValue.java:183)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue.access$200(ReviewboardParameterValue.java:51)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ReviewboardBuildWrapper.setUp(ReviewboardParameterValue.java:227)
	at hudson.model.Build$BuildExecution.doRun(Build.java:154)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
	at hudson.model.Run.execute(Run.java:1718)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: com.cloudbees.diff.PatchException: Cannot apply hunk @@ 7
	at com.cloudbees.diff.ContextualPatch.applyHunk(ContextualPatch.java:228)
	at com.cloudbees.diff.ContextualPatch.applyPatch(ContextualPatch.java:155)
	at com.cloudbees.diff.ContextualPatch.patch(ContextualPatch.java:108)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ApplyTask.invoke(ReviewboardParameterValue.java:246)
	... 12 more
FATAL: Failed to patch /usr0/jenkins/jobs/ting-trunk job02b -- parameterized build/workspace/test/pan/log/test_panlog.py
java.io.IOException: Failed to patch /usr0/jenkins/jobs/ting-trunk job02b -- parameterized build/workspace/test/pan/log/test_panlog.py
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ApplyTask.invoke(ReviewboardParameterValue.java:250)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ApplyTask.invoke(ReviewboardParameterValue.java:240)
	at hudson.FilePath.act(FilePath.java:989)
	at hudson.FilePath.act(FilePath.java:967)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue.applyPatch(ReviewboardParameterValue.java:183)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue.access$200(ReviewboardParameterValue.java:51)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ReviewboardBuildWrapper.setUp(ReviewboardParameterValue.java:227)
	at hudson.model.Build$BuildExecution.doRun(Build.java:154)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
	at hudson.model.Run.execute(Run.java:1718)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: com.cloudbees.diff.PatchException: Cannot apply hunk @@ 7
	at com.cloudbees.diff.ContextualPatch.applyHunk(ContextualPatch.java:228)
	at com.cloudbees.diff.ContextualPatch.applyPatch(ContextualPatch.java:155)
	at com.cloudbees.diff.ContextualPatch.patch(ContextualPatch.java:108)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ApplyTask.invoke(ReviewboardParameterValue.java:246)
	... 12 more

**Comment by moorecm** [comment]
FYI, that patch failed because I used an old review (the change was already pushed into the shared repo.).  The plugin is working for me now (I just have to clone the workspace for the downstream jobs).

Thank you!

**Comment by yardena** [comment]
Glad it worked :-)
