### ISSUE TITLE
Can the Review URL parameter be optional?

### ISSUE THREAD

**Issue by moorecm** [vmware/jenkins-reviewbot#19]
I'm trying to configure 2 workflows:
1) a set of SCM triggered jobs for the shared repo.
2) a set of jenkins-reviewbot triggered jobs for sandbox (not yet pushed to the shared repo.) changes

Ideally, these workflows would share the jobs after a workspace is created.  For example, it would be nice to have the SCM trigger start the same jobs (parameterized by review url) but the plugin fails if the review url is null:
FATAL: null
java.lang.NullPointerException
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.getProperties(ReviewboardConnection.java:218)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue.buildEnvVars(ReviewboardParameterValue.java:199)
	at hudson.model.ParameterValue.buildEnvironment(ParameterValue.java:173)
	at hudson.model.ParametersAction.buildEnvVars(ParametersAction.java:88)
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:929)
	at hudson.plugins.mercurial.MercurialSCM.checkout(MercurialSCM.java:528)
	at hudson.scm.SCM.checkout(SCM.java:484)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
	at hudson.model.Run.execute(Run.java:1718)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)

Is there a way to make it keep going and just skip the patching/result logic if the review was not specified?

**Comment by misery** [comment]
You need to add "Current build parameters" to the trigger build job for alle downstream jobs.

**Comment by moorecm** [comment]
If a downstream job (using its own workspace directory) gets the review_url parameter like that, without explicitly being "parameterized by review_url", will it get and apply the patch in its workspace?

**Comment by moorecm** [comment]
It does.  Your suggestion works great!  This is the kind of thing that should just be available in the documentation, though.  Some nontrivial example configuration would be a huge help.
