### ISSUE TITLE
UnmarshalException

### ISSUE THREAD

**Issue by misery** [vmware/jenkins-reviewbot#20]
Hi there again! :-/

I have a problem if I want to start some more jobs at the same time. I added a multijob that will download the patch und check if everything is fine with it. After that it will trigger 5 other jobs that will download the patch, too. These jobs will be triggered at the same time. After some seconds they will stop building with those exceptions:

```
09:35:59 FATAL: javax.xml.bind.UnmarshalException: unerwartetes Element (URI:"", lokal:"method"). Erwartete Elemente sind <{}rsp>
09:35:59 java.lang.RuntimeException: javax.xml.bind.UnmarshalException: unerwartetes Element (URI:"", lokal:"method"). Erwartete Elemente sind <{}rsp>
09:35:59 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.unmarshalResponse(ReviewboardConnection.java:346)
09:35:59 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.getProperties(ReviewboardConnection.java:223)
09:35:59 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue.buildEnvVars(ReviewboardParameterValue.java:204)
09:35:59 	at hudson.model.ParameterValue.buildEnvironment(ParameterValue.java:173)
09:35:59 	at hudson.model.ParametersAction.buildEnvVars(ParametersAction.java:88)
09:35:59 	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:929)
09:35:59 	at hudson.plugins.mercurial.MercurialSCM.checkout(MercurialSCM.java:550)
09:35:59 	at hudson.scm.SCM.checkout(SCM.java:484)
09:35:59 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
09:35:59 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
09:35:59 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
09:35:59 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
09:35:59 	at hudson.model.Run.execute(Run.java:1751)
09:35:59 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
09:35:59 	at hudson.model.ResourceController.execute(ResourceController.java:89)
09:35:59 	at hudson.model.Executor.run(Executor.java:240)
09:35:59 Caused by: javax.xml.bind.UnmarshalException: unerwartetes Element (URI:"", lokal:"method"). Erwartete Elemente sind <{}rsp>
09:35:59 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726)
09:35:59 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247)
09:35:59 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242)
09:35:59 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109)
09:35:59 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1131)
09:35:59 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556)
09:35:59 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
09:35:59 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
09:35:59 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
09:35:59 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:379)
09:35:59 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:605)
09:35:59 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3138)
09:35:59 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880)
09:35:59 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
09:35:59 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
09:35:59 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
09:35:59 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
09:35:59 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
09:35:59 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
09:35:59 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
09:35:59 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
09:35:59 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
09:35:59 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
09:35:59 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
09:35:59 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)
09:35:59 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.unmarshalResponse(ReviewboardConnection.java:344)
09:35:59 	... 15 more
09:35:59 Skipped archiving because build is not successful
```

```
FATAL: Connection is not open
09:35:58 java.lang.IllegalStateException: Connection is not open
09:35:58 	at org.apache.commons.httpclient.HttpConnection.assertOpen(HttpConnection.java:1277)
09:35:58 	at org.apache.commons.httpclient.HttpConnection.write(HttpConnection.java:974)
09:35:58 	at org.apache.commons.httpclient.HttpConnection.write(HttpConnection.java:943)
09:35:58 	at org.apache.commons.httpclient.HttpConnection.writeLine(HttpConnection.java:1002)
09:35:58 	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2061)
09:35:58 	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
09:35:58 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
09:35:58 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
09:35:58 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
09:35:58 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
09:35:58 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.ensureAuthentication(ReviewboardConnection.java:134)
09:35:58 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.ensureAuthentication(ReviewboardConnection.java:126)
09:35:58 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.getProperties(ReviewboardConnection.java:222)
09:35:58 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue.buildEnvVars(ReviewboardParameterValue.java:204)
09:35:58 	at hudson.model.ParameterValue.buildEnvironment(ParameterValue.java:173)
09:35:58 	at hudson.model.ParametersAction.buildEnvVars(ParametersAction.java:88)
09:35:58 	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:929)
09:35:58 	at hudson.plugins.mercurial.MercurialSCM.checkout(MercurialSCM.java:536)
09:35:58 	at hudson.scm.SCM.checkout(SCM.java:484)
09:35:58 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
09:35:58 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
09:35:58 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
09:35:58 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
09:35:58 	at hudson.model.Run.execute(Run.java:1751)
09:35:58 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
09:35:58 	at hudson.model.ResourceController.execute(ResourceController.java:89)
09:35:58 	at hudson.model.Executor.run(Executor.java:240)
09:35:58 Skipped archiving because build is not successful
```

If I start these jobs manually with some seconds between the start it will work flawlessly. I wrote a little test shell script to check the connection to the reviewboard without jenkins. It started 100 parallel GET-Requests without problems. So it seems that it isn't a reviewboard-server problem.

Any hints? Are there some timing problems with parallel execution?

Thanks!

**Comment by yardena** [comment]
Yes, it's a problem with parallel execution.

**Comment by yardena** [comment]
@misery could you please try with latest master code and tell me if it fixed the issue?

**Comment by misery** [comment]
Looks like it is fixed here! :-) Thank you very much!

**Comment by misery** [comment]
Well, I got another exception. I don't know why this happend. I can't see that there were a parallel connection as this build was some minutes after the fat build.


```
17:22:36 FATAL: java.net.SocketException: Connection reset
17:22:36 java.lang.RuntimeException: java.net.SocketException: Connection reset
17:22:36 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.getResponse(ReviewboardConnection.java:371)
17:22:36 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.getProperties(ReviewboardConnection.java:249)
17:22:36 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue.buildEnvVars(ReviewboardParameterValue.java:207)
17:22:36 	at hudson.model.ParameterValue.buildEnvironment(ParameterValue.java:173)
17:22:36 	at hudson.model.ParametersAction.buildEnvVars(ParametersAction.java:88)
17:22:36 	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:929)
17:22:36 	at hudson.plugins.mercurial.MercurialSCM.checkout(MercurialSCM.java:551)
17:22:36 	at hudson.scm.SCM.checkout(SCM.java:484)
17:22:36 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
17:22:36 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
17:22:36 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
17:22:36 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
17:22:36 	at hudson.model.Run.execute(Run.java:1751)
17:22:36 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
17:22:36 	at hudson.model.ResourceController.execute(ResourceController.java:89)
17:22:36 	at hudson.model.Executor.run(Executor.java:240)
17:22:36 Caused by: java.net.SocketException: Connection reset
17:22:36 	at java.net.SocketInputStream.read(SocketInputStream.java:209)
17:22:36 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
17:22:36 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
17:22:36 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
17:22:36 	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
17:22:36 	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
17:22:36 	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
17:22:36 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
17:22:36 	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
17:22:36 	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
17:22:36 	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
17:22:36 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
17:22:36 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
17:22:36 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
17:22:36 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
17:22:36 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.getResponse(ReviewboardConnection.java:362)
17:22:36 	... 15 more
```

**Comment by yardena** [comment]
I made few more changes.

**Comment by misery** [comment]
Looks like that there are some more problems.

```
FATAL: Connection factory has been shutdown.
java.lang.IllegalStateException: Connection factory has been shutdown.
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager.doGetConnection(MultiThreadedHttpConnectionManager.java:463)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager.getConnectionWithTimeout(MultiThreadedHttpConnectionManager.java:416)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:153)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.ensureAuthentication(ReviewboardConnection.java:143)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.ensureAuthentication(ReviewboardConnection.java:135)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.execDiffMethod(ReviewboardConnection.java:159)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.access$100(ReviewboardConnection.java:55)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection$DiffHandle.getStream(ReviewboardConnection.java:182)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ReviewboardBuildWrapper.setUp(ReviewboardParameterValue.java:203)
	at hudson.model.Build$BuildExecution.doRun(Build.java:154)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
```
