### ISSUE TITLE
Connection factory has been shutdown

### ISSUE THREAD

**Issue by misery** [vmware/jenkins-reviewbot#24]
As mentioned in issue #20 I create a new issue for this as this will happen sporadically since that issue was fixed.

Seems like another parallel execution problem.

```
14:22:01 FATAL: Connection factory has been shutdown.
14:22:01 java.lang.IllegalStateException: Connection factory has been shutdown.
14:22:01 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager.doGetConnection(MultiThreadedHttpConnectionManager.java:463)
14:22:01 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager.getConnectionWithTimeout(MultiThreadedHttpConnectionManager.java:416)
14:22:01 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:153)
14:22:01 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
14:22:01 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
14:22:01 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.ensureAuthentication(ReviewboardConnection.java:143)
14:22:01 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.ensureAuthentication(ReviewboardConnection.java:135)
14:22:01 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.execDiffMethod(ReviewboardConnection.java:159)
14:22:01 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.access$100(ReviewboardConnection.java:55)
14:22:01 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection$DiffHandle.getStream(ReviewboardConnection.java:182)
14:22:01 	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ReviewboardBuildWrapper.setUp(ReviewboardParameterValue.java:203)
14:22:01 	at hudson.model.Build$BuildExecution.doRun(Build.java:154)
14:22:01 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
14:22:01 	at hudson.model.Run.execute(Run.java:1741)
14:22:01 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
14:22:01 	at hudson.model.ResourceController.execute(ResourceController.java:98)
14:22:01 	at hudson.model.Executor.run(Executor.java:374)
```

**Comment by misery** [comment]
Maybe it is a problem with the poller-job... it got this exception in another job but at another time.


```
java.lang.RuntimeException: java.net.SocketException: Connection reset
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.getResponse(ReviewboardConnection.java:375)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.access$300(ReviewboardConnection.java:55)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection$2.apply(ReviewboardConnection.java:278)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection$2.apply(ReviewboardConnection.java:276)
	at com.google.common.collect.Iterators$8.next(Iterators.java:812)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:648)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators.size(Iterators.java:151)
	at com.google.common.collect.Collections2$FilteredCollection.size(Collections2.java:222)
	at com.google.common.collect.Collections2$TransformedCollection.size(Collections2.java:288)
	at java.util.HashSet.<init>(HashSet.java:118)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardPollingBuilder.perform(ReviewboardPollingBuilder.java:114)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.Build$BuildExecution.build(Build.java:203)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardConnection.getResponse(ReviewboardConnection.java:366)
	... 21 more
```

**Comment by yardena** [comment]
Should be fixed now
